// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20201026201300_SeedData1")]
    partial class SeedData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Details");

                    b.Property<int>("Rating");

                    b.Property<string>("UserName");

                    b.Property<DateTime>("Visited");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Seattle",
                            Country = "USA",
                            Details = "A City in the Pacific Northwest surrounded by hills and trees.",
                            Rating = 4,
                            UserName = "mmanchee",
                            Visited = new DateTime(2020, 10, 26, 13, 13, 0, 229, DateTimeKind.Local).AddTicks(3437)
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Stockholm",
                            Country = "Sweden",
                            Details = "A City in northern Europe. Sweden's Capitol.",
                            Rating = 5,
                            UserName = "gbrown",
                            Visited = new DateTime(2020, 10, 26, 13, 13, 0, 229, DateTimeKind.Local).AddTicks(3437)
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Toronto",
                            Country = "Canada",
                            Details = "Canada's most populated city, located just beyond the border near Detroit.",
                            Rating = 4,
                            UserName = "gbrown",
                            Visited = new DateTime(2020, 10, 26, 13, 13, 0, 229, DateTimeKind.Local).AddTicks(3437)
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Shanghai",
                            Country = "China",
                            Details = "A city in China that neighbors Hong-Kong just on the other side of the river.",
                            Rating = 4,
                            UserName = "gbrown",
                            Visited = new DateTime(2020, 10, 26, 13, 13, 0, 229, DateTimeKind.Local).AddTicks(3437)
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Honolulu",
                            Country = "USA",
                            Details = "Located in the middle of the Pacific near the equator. This coast city sits right on white sand beaches with Diamond Head Mt. at the far south",
                            Rating = 5,
                            UserName = "mmanchee",
                            Visited = new DateTime(2020, 10, 26, 13, 13, 0, 229, DateTimeKind.Local).AddTicks(3437)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
